name: UserService
services: 
  user_service_postgres:
    image: postgres
    container_name: user_service_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
      - ./postgres-initdb:/docker-entrypoint-initdb.d
